# Generated by Django 2.2.5 on 2019-10-02 16:36

from django.db import migrations, models
import socialtoken.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=socialtoken.models.get_uid, max_length=12)),
                ('oauth_token', models.TextField()),
                ('oauth_token_secret', models.TextField()),
            ],
        ),
    ]
